// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqqbhczikqqgglugeknf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcWJoY3ppa3FxZ2dsdWdla25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODQzMDcsImV4cCI6MjA3NDE2MDMwN30.sAVjkpLCp6WD5drkYflZNyKjQpVFtlmO1KOP4RssNbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});